name: Deploy 

on:
  push:
    branches:
      - main   # se ejecuta solo cuando hay push a main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Deploy en servidor
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}        # IP o dominio de tu servidor
          username: ${{ secrets.SSH_USER }}    # usuario del servidor (ej: mateo_gonzalez)
          key: ${{ secrets.SSH_KEY }}          # clave privada (id_ed25519)
          port: 22
          script: |
            cd ~/lemp-sites/***   # ajusta la ruta a tu proyecto
            git pull origin main
            # podés agregar más comandos si querés (ej: npm install, docker-compose, etc.)
